default_stages: [commit]
exclude: '^data/'
ci:
  autoupdate_commit_msg: "chore(deps): pre-commit.ci autoupdate"
  autoupdate_schedule: "monthly"
  autofix_commit_msg: "style: pre-commit.ci fixes"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3
        args: [--preview]
      - id: black-jupyter
        language_version: python3
        args: [--preview]
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-use-pathlib
          - flake8-bugbear
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile, black, --multi-line, "3"]
  - repo: https://github.com/PyCQA/pylint
    rev: v2.16.4
    hooks:
      - id: pylint
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.2
    hooks:
      - id: shellcheck
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
